name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  readme-path:
    description: 'Path to README file to change'
    required: false
    default: './README.md'
  coverage-summary-path:
    description: 'path to file that has coverage summary in it'
    required: false
    default: './coverage/coverage-summary.json'
  disable-commit:
    description: 'path to file that has coverage summary in it'
    required: false
    default: false
outputs:
  result:
    description: 'Outputs the result of an actions, could be false or true'
    
runs:
  using: 'node12'
  main: 'build/index.js'
