name: Build update coverage badge

on:
  push:
    paths:
      - update-coverage-badge/**
      - .github/workflows/build-update-coverage-badge.yml
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instal dependencies
        run: npm install --prefix update-coverage-badge

      - name: Run tests
        run: npm run test --prefix update-coverage-badge

      - name: build app
        run: rm -rf ./update-coverage-badge/build && npm run build --prefix update-coverage-badge
