name: Build update d2c service

on:
  push:
    paths:
      - 'update-d2c-service/**'
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instal dependencies
        run: npm install --prefix update-d2c-service

      - name: Run tests
        run: npm run test --prefix update-d2c-service

      - name: build app
        run: rm -rf ./update-d2c-service/build && npm run build --prefix update-d2c-service

      - name: push build folder to git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./update-d2c-service/build ./update-d2c-service/node_modules
          git commit -m "Added build and node_modules folder to update-d2c-service action"
          git push
