name: Build update coverage badge

on:
  push:
    paths:
      - 'update-coverage-badge/*'
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instal dependencies
        run: npm install --prefix update-coverage-badge

      - name: Run tests
        run: npm run test --prefix update-coverage-badge

      - name: build app
        run: rm -rf ./update-coverage-badge/build && npm run build --prefix update-coverage-badge

      - name: push build folder to git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./update-coverage-badge/build ./update-coverage-badge/node_modules
          git commit -m "Added build and node_modules folder to update-coverage-badge action"
          git push
