name: Build update d2c service

on:
  push:
    paths:
      - update-d2c-service/**
      - .github/workflows/build-update-d2c-service.yml
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instal dependencies
        run: npm install --prefix update-d2c-service

      - name: Run tests
        run: npm run test --prefix update-d2c-service

      - name: build app
        run: rm -rf ./update-d2c-service/build && npm run build --prefix update-d2c-service
