name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instal dependencies
        run: npm install --prefix update-coverage-badge

      - name: build app
        run: rm -rf ./update-coverage-badge/build && npm run build --prefix update-coverage-badge

      - name: Run tests with coverage for update-coverage-badge
        run: |
          cd ./update-coverage-badge
          npm run test:coverage

      - uses: ./update-coverage-badge
        readme-path: ./update-coverage-badge/README.md
        coverage-summary-path: ./update-coverage-badge/coverage/coverage-summary.json
